name: Playwright Cucumber BDD Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install @cucumber/cucumber playwright @cucumber/pretty-formatter chai

      # Step 4: Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Step 5: Run Cucumber tests
      - name: Run Cucumber Playwright tests
        run: npx cucumber-js --require step-definitions/**/*.js --require support/**/*.js --format json:reports/cucumber-report.json

      # Step 6: Upload test reports as artifacts (optional)
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: reports/

      # Step 7: Deploy HTML report to GitHub Pages
      - name: Deploy HTML Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BDDTOKEN }}
          publish_dir: reports/
          publish_branch: gh-pages
          
      - name: Generate HTML Report
        run: node generate-report.js