name: Playwright Cucumber BDD Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust if necessary

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libgbm1 libasound2

      - name: Install dependencies (Cucumber, Playwright, Gherkin, Chai)
        run: npm install --save-dev @cucumber/cucumber playwright @cucumber/pretty-formatter chai

      - name: Grant Playwright Permission
        run: chmod +x node_modules/.bin/playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber Playwright Tests
        run: npx cucumber-js --require step-definitions/**/*.js --require support/**/*.js --format @cucumber/pretty-formatter

      - name: Upload Cucumber Reports (JSON & JUnit)
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: reports/

      - name: Deploy HTML Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BDDTOKEN }}  # Changed from BDDTOKEN
          publish_dir: reports/
          publish_branch: gh-pages
